name: Update Changelog

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get tag name
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Update Changelog
        run: |
          # Get release information
          TAG_NAME="${{ steps.tag.outputs.tag_name }}"
          if [ "${{ github.event_name }}" = "release" ]; then
            RELEASE_BODY="${{ github.event.release.body }}"
          else
            RELEASE_BODY="No release notes provided."
          fi
          RELEASE_DATE=$(date -u +%Y-%m-%d)
          REPO_NAME="${{ github.repository }}"

          # Update Unreleased link to point to the new tag
          sed -i "s|## \[Unreleased\](.*)|## [Unreleased](https://github.com/${REPO_NAME}/compare/${TAG_NAME}...main)|" CHANGELOG.md

          # Create new release entry
          {
            echo "## [${TAG_NAME}](https://github.com/${REPO_NAME}/compare/v0.0.2...${TAG_NAME}) - ${RELEASE_DATE}"
            echo ""
            echo "$RELEASE_BODY"
            echo ""
          } > new_release_entry.md

          # Read the current changelog and insert the new entry after the first two lines
          {
            head -n 2 CHANGELOG.md
            echo ""
            cat new_release_entry.md
            tail -n +3 CHANGELOG.md
          } > temp_changelog.md

          mv temp_changelog.md CHANGELOG.md

      - name: Commit and push
        run: |
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for ${TAG_NAME}"
          git push
